import libary The library that will be required

In [13]:
import pandas as pd
import numpy as np

Pandas has two objects, namely series and data frames

OBJECT SERIES

Serie objects have one dimension. They don't have a column because they only have one column. And they have an index.


In [14]:
data = [0.25, 0.50, 0.75, 1]

In [15]:
print(data)

[0.25, 0.5, 0.75, 1]


In [16]:
data = pd.Series(data)

In [17]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [18]:
data[2]

0.75

In [10]:
data.values #want to release the value

array([0.25, 0.5 , 0.75, 1.  ])

displays index. The index is in the form of a range, where the start point is included in the range and the stop point is exclusive to the range.

In [11]:
data.index #index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
list(range(1,10))

how to call data

In [10]:
data[2] # name slicing

12

Implicit index is the default index. we can define the index, this is called the defined explicit index.

In [12]:
data = pd.Series([0.25, 0.50, 0.75, 1], index=['a','b','c','d'])

In [13]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

how to call data

In [16]:
#from the explicit index it calls

data['a']

0.25

This is data selection

Even though we have created an explicit index, we can still call the implicit index.

In [17]:
#indeks implisitnya

data[3]

1.0

when the implicit index and explicit index are the same, when we are calling the data it will only rely on the explicit index

In [18]:
data_2 = pd.Series([0.25, 0.50, 0.75, 1], index=[2,5,3,7])

In [20]:
data_2[2] #calls according to explicit data (index)

0.25

In [21]:
data_2[0]

KeyError: 0

Let's try slicing again

In [34]:
data_2 = pd.Series([0.25, 0.50, 0.75, 1], index=['a','b','c','d'])

In [35]:
data_2

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

suppose we will call from b - c

In [36]:
data_2['b':'c']

b    0.50
c    0.75
dtype: float64

but if we slice the implicit index, it will only appear when the start is a range

In [37]:
data_2[1:2]

b    0.5
dtype: float64

In [ ]:
TASK1 & TASK2 - HARI SELASA

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [0.10, 2>6, 12, 1+2j, 'my edusolve', 0.20, 5>3]

In [3]:
print(data)

[0.1, False, 12, (1+2j), 'my edusolve', 0.2, True]


In [4]:
data = pd.Series(data)

In [5]:
data

0            0.1
1          False
2             12
3         (1+2j)
4    my edusolve
5            0.2
6           True
dtype: object

In [6]:
data.values #task2

array([0.1, False, 12, (1+2j), 'my edusolve', 0.2, True], dtype=object)

In [7]:
data.index #task2

RangeIndex(start=0, stop=7, step=1)

In [8]:
data[0:5] #task2

0            0.1
1          False
2             12
3         (1+2j)
4    my edusolve
dtype: object

In [9]:
data[3:9] #task2

3         (1+2j)
4    my edusolve
5            0.2
6           True
dtype: object

TASK3 - HARI SELASA

In [1]:
import pandas as pd
import numpy as np

In [10]:
absen = pd.Series([1, 10, 8, 9], index=['daniel','dyah','arum','aulia'])

In [11]:
absen

daniel     1
dyah      10
arum       8
aulia      9
dtype: int64

In [12]:
absen.values

array([ 1, 10,  8,  9], dtype=int64)

In [14]:
absen.index

Index(['daniel', 'dyah', 'arum', 'aulia'], dtype='object')

In [15]:
absen['aulia']

9

In [17]:
absen[1]

10

In [ ]:
TASK4 - HARI SELASA

In [29]:
X =pd.Series([0.20, 30.7, 100,0.50, 4.10, 12, 'data analyst', 10, 26, 3+5j], index =[1,5,7,6,8,9,2,3,11,4])

In [31]:
X

1              0.2
5             30.7
7              100
6              0.5
8              4.1
9               12
2     data analyst
3               10
11              26
4           (3+5j)
dtype: object

In [32]:
X[5]

30.7

In [33]:
X[0]

KeyError: 0

TASK5

In [18]:
data =pd.Series([0.20, 30.7, 100,0.50, 4.10, 12, 'data analyst', 10, 26, 3+5j], index =['a','b','c','d','e','f','g','h','i','j'])

In [19]:
data

a             0.2
b            30.7
c             100
d             0.5
e             4.1
f              12
g    data analyst
h              10
i              26
j          (3+5j)
dtype: object

In [20]:
data['a':'d']

a     0.2
b    30.7
c     100
d     0.5
dtype: object

In [21]:
data[1:6:2] # 3parameter implisit

b    30.7
d     0.5
f      12
dtype: object

In [22]:
data[3:8:3] #3parameter

d             0.5
g    data analyst
dtype: object

In [44]:
data[6:9] #parameter

g    data analyst
h              10
i              26
dtype: object